# .github/workflows/block-non-dev-prs.yml
name: Allow Only PRs from Development

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from development
        run: |
          echo "PR source branch: ${{ github.head_ref }}"
          if [[ "${{ github.head_ref }}" != "development" ]]; then
            echo "Only pull requests from 'development' to 'main' are allowed."
            exit 1
          fi
