name: Go Build Check

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # speeds up CI

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Verify Go version
        run: go version

      - name: Install Templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Generate Templ files
        run: templ generate

      - name: Tidy (optional cleanup)
        run: go mod tidy

      - name: Build the project
        run: go build ./...
